project:
  type: book

book:
  title: "R Data Manipulation Booklet"
  author: "Mohammed Hamdy"
  date: "11/19/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - firstlook.qmd
    - subset.qmd
    - transform.qmd
    - aggregate.qmd
    - reshape.qmd
    - merge.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



